all:
	g++ -g extractor.cc -I/home/aniket/meta_compiler/tools/rose/boost_1_61_0/include -I/home/aniket/meta_compiler/tools/rose/rose_build/include/rose -L/home/aniket/meta_compiler/tools/rose/rose_build/lib/ -lrose -lboost_iostreams -lboost_system -o run_extactor
